### ISSUE TITLE
ts提示错误TS2345

### ISSUE THREAD

**Issue by DexYang** [hsiangleev/element-plus-admin#1]
您好，我用webstorm加载这个工程的时候，main.ts提示这个错误，你知道为什么吗？
![image](https://user-images.githubusercontent.com/22140560/106118150-c4cdbd00-618e-11eb-8bf9-84f3063a066f.png)

**Comment by hsiangleev** [comment]
@DeluxeYang 我这边看不到你的那个图片，可以直接发一个图片地址吗
