### ISSUE TITLE
typescript 文件老提示找不到模块的

### ISSUE THREAD

**Issue by mx4g** [hsiangleev/element-plus-admin#13]
typescript 文件老提示找不到模块的，但是可以运行！是不是缺少了什么配置？还是我的VSCode少了什么配置？百度不到解决方案，特地来问大佬；
![image](https://user-images.githubusercontent.com/7499986/125181914-0aada780-e23c-11eb-8d96-f0ce9f12fc84.png)

**Comment by hsiangleev** [comment]
@mx4g 你的tsconfig.json文件里面的path配置有没有改
```javascript
"paths": {
    "/@/*": ["src/*"],
    "/mock/*": ["mock/*"],
    "/server/*": ["server/*"]
}
```
这个没改的话应该不会出现吧

**Comment by mx4g** [comment]
> @mx4g 你的tsconfig.json文件里面的path配置有没有改
> 
> ```js
> "paths": {
>     "/@/*": ["src/*"],
>     "/mock/*": ["mock/*"],
>     "/server/*": ["server/*"]
> }
> ```
> 
> 这个没改的话应该不会出现吧

这个没有改，我下载下来直接运行，就这样了！是不是VSCode要装什么插件呢？

**Comment by hsiangleev** [comment]
@mx4g 插件的话，除了vetur和volar两个二选一，其它的插件我这边全都禁用之后也没有出现这个错误，你上面显示的报错信息是什么，可以发一下吗

**Comment by mx4g** [comment]
VSCode 鼠标放上去提示： Cannot find module '/@/utils/formExtend' ，它就提示这样的错误！

**Comment by mx4g** [comment]
> @mx4g 插件的话，除了vetur和volar两个二选一，其它的插件我这边全都禁用之后也没有出现这个错误，你上面显示的报错信息是什么，可以发一下吗

VSCode 鼠标放上去提示： Cannot find module '/@/utils/formExtend' ，它就提示这样的错误！奇怪了，就不知道怎么回事。

**Comment by hsiangleev** [comment]
@mx4g 报错信息后面还有哪一个插件抛出来的错误来，类似这个![](https://images.hsianglee.cn//img/2021/07/12/20210712144652.png)
你的这个错误信息后面是什么

**Comment by mx4g** [comment]
> @mx4g 报错信息后面还有哪一个插件抛出来的错误来，类似这个![](https://camo.githubusercontent.com/1821e4bc7ba58b68e5074841da551da66f42841d89ca6d02e5d6fc8e5df6d2a1/68747470733a2f2f696d616765732e687369616e676c65652e636e2f2f696d672f323032312f30372f31322f32303231303731323134343635322e706e67)
> 你的这个错误信息后面是什么

奇怪，我显示跟你不一样！
![image](https://user-images.githubusercontent.com/7499986/125244741-41f68400-e322-11eb-87f9-3e285a205fcd.png)
查看问题点进去后：
![image](https://user-images.githubusercontent.com/7499986/125244700-36a35880-e322-11eb-87e6-6ef0245f1535.png)
Paths配置：
![image](https://user-images.githubusercontent.com/7499986/125244819-5aff3500-e322-11eb-9642-81e0a9b48dd6.png)

**Comment by mx4g** [comment]
> @mx4g 报错信息后面还有哪一个插件抛出来的错误来，类似这个![](https://camo.githubusercontent.com/1821e4bc7ba58b68e5074841da551da66f42841d89ca6d02e5d6fc8e5df6d2a1/68747470733a2f2f696d616765732e687369616e676c65652e636e2f2f696d672f323032312f30372f31322f32303231303731323134343635322e706e67)
> 你的这个错误信息后面是什么
没有显示那个后缀
