### ISSUE TITLE
页面刷新后标签栏异常

### ISSUE THREAD

**Issue by yang-sanmu** [hsiangleev/element-plus-admin#14]
如打开3个标签，F5刷新页面，标签栏仅剩最后一个标签。
且剩余的这个标签变成了固定标签，没有关闭按钮

刷新前
![image](https://user-images.githubusercontent.com/75962675/129522081-e4e6f13d-9600-477d-9bba-79a71fc9f482.png)

刷新后
![image](https://user-images.githubusercontent.com/75962675/129522129-80582a8d-46db-49f0-b3d0-8c53c0863e5d.png)

**Comment by hsiangleev** [comment]
@sanmu-sen 这个应该不算异常吧
1. 标签栏是设计的时候就是刷新整个页面只保留最后一个
2. 没有关闭按钮是因为只剩最后一个标签栏，所以才不给关闭

**Comment by yang-sanmu** [comment]
谢谢，我以为没有关闭按钮是 “固定标签” 这种设计。
