### ISSUE TITLE
升级element-plus 到最新版本，无法运行

### ISSUE THREAD

**Issue by libra1010** [hsiangleev/element-plus-admin#15]
升级element-plus 到最新版本后，出现无法运行，不知道是不是vite的原因
什么时候能升级吗？
后端人员看这个有点头疼啊
![image](https://user-images.githubusercontent.com/9667153/131099813-b72ab629-8853-45ac-8ab6-cfc9760b9816.png)

**Comment by libra1010** [comment]
好像是样式地址变了
改成这个就行了　import 'element-plus/dist/index.css'
不知道具体对不对

**Comment by hsiangleev** [comment]
@libra1010 刚更新了一下，改动了四个文件，可以看一下[https://github.com/hsiangleev/element-plus-admin/commit/4ed2540ddd84813691db6cfdfe1fc7cd3da561ea](https://github.com/hsiangleev/element-plus-admin/commit/4ed2540ddd84813691db6cfdfe1fc7cd3da561ea)
