### ISSUE TITLE
登录dev或者test角色  访问admin的路由为什么没有跳到401而跳到404

### ISSUE THREAD

**Issue by lcrabs** [hsiangleev/element-plus-admin#16]

**Comment by hsiangleev** [comment]
@lcrabs 
1. 因为这个404的跳转是前台处理的，使用dev角色登陆的时候，后台返回的页面前台并不知道其它角色是否有。
2. 这个也是仿照[vue-element-admin](https://panjiachen.github.io/vue-element-admin/#/permission/page)做的，他也是跳转404。
