### ISSUE TITLE
一直报这个无法引用的问题

### ISSUE THREAD

**Issue by mx4g** [hsiangleev/element-plus-admin#17]
我这个问题一直无法解决，你的vscode 的 settings.json是怎么设置的，能不能分享一下？
![image](https://user-images.githubusercontent.com/7499986/137628562-67315f4f-6e85-44ae-a59a-b382e5852535.png)

**Comment by hsiangleev** [comment]
@mx4g 这个应该是插件的问题吧，你现在用的是volar插件吗，可以先禁用一下，然后试试用vetur插件试试看还报这个错误不
