### ISSUE TITLE
src/layout/components/tags.vue:8:22  :ref='getTagsDom'

### ISSUE THREAD

**Issue by endypark** [hsiangleev/element-plus-admin#20]
build的时候，有个报错，，这里 报错太复杂，看不清楚啥问题

**> vue-tsc --noEmit --skipLibCheck && vite build**

src/layout/components/tags.vue:8:22 - error TS2322: Type '(el: ComponentInternalInstance | Element | null) => number | null' is not assignable to type 'string | Ref<any> | ((ref: Element | ComponentPublicInstance<{}, {}, {}, {}, {}, {}, {}, {}, false, ComponentOptionsBase<any, any, any, any, any, any, any, any, any, {}>> | null) => void) | undefined'.
  Type '(el: ComponentInternalInstance | Element | null) => number | null' is not assignable to type '(ref: Element | ComponentPublicInstance<{}, {}, 
{}, {}, {}, {}, {}, {}, false, ComponentOptionsBase<any, any, any, any, any, any, any, any, any, {}>> | null) => void'.
    Types of parameters 'el' and 'ref' are incompatible.
      Type 'Element | ComponentPublicInstance<{}, {}, {}, {}, {}, {}, {}, {}, false, ComponentOptionsBase<any, any, any, any, any, any, any, any, any, {}>> | null' is not assignable to type 'ComponentInternalInstance | Element | null'.
        Type 'ComponentPublicInstance<{}, {}, {}, {}, {}, {}, {}, {}, false, ComponentOptionsBase<any, any, any, any, any, any, any, any, any, {}>>' is not assignable to type 'ComponentInternalInstance | Element | null'.
          Type 'ComponentPublicInstance<{}, {}, {}, {}, {}, {}, {}, {}, false, ComponentOptionsBase<any, any, any, any, any, any, any, any, any, {}>>' is missing the following properties from type 'Element': attributes, classList, className, clientHeight, and 160 more.

8                     :ref='getTagsDom'
                       ~~~

Found 1 error.

应该是 ts 校验 数据类型不匹配

**Comment by endypark** [comment]
v-for='v in tagsList' :ref='getTagsDom'
getTagsDom = (el: ComponentInternalInstance | Element | null) => xxxxx
这里的 el 应该是 ITagsList， 在这里被强制 转成了 ComponentInternalInstance | Element | null， 所以报错
具体 怎么解决，还没搞清楚 这里是 做什么的，还没敢随便改

**Comment by endypark** [comment]
// const getTagsDom = (el:ComponentInternalInstance | Element | null) => el && layoutTagsItem.value.push(el)// error while npm-run-build
    const getTagsDom = (el:any) => el && layoutTagsItem.value.push(el)
    这样 vue-tsc 可以通过，，但是 感觉 这是 一种 【非正规】 解决办法

**Comment by hsiangleev** [comment]
@endypark 
- 不好意思，最近一直再忙工作的事情，没怎么看这个
- 我这边生成的时候好像一直都没有报这个错
- 这个是为了获取dom节点，然后计算横向滚动条位置的，但是现在好像不需要这个代码了，删掉应该也可以，上次更新vue和elementPlus的时候没有细看，后面有时间的时候再改一下
