### ISSUE TITLE
vscode 编辑器提示的警告⚠️，应该怎么解决？

### ISSUE THREAD

**Issue by AsherSun** [hsiangleev/element-plus-admin#21]
![image](https://user-images.githubusercontent.com/28916706/161926851-c4bbd9b2-9250-4ed2-a26c-8cd61658b202.png)

**Comment by hsiangleev** [comment]
@AsherSun 你用的vscode的插件是volar吗，你换成vetur试试会报错吗

**Comment by coderachel** [comment]
有什么办法可以使用volar，又不会报错吗？

**Comment by hsiangleev** [comment]
@coderachel 你可以看一下这个[https://github.com/johnsoncodehk/volar/issues/335](https://github.com/johnsoncodehk/volar/issues/335)，我也好久没关注这个了
