### ISSUE TITLE
使用yarn 或者pnpm 运行出来样式不正确

### ISSUE THREAD

**Issue by libra1010** [hsiangleev/element-plus-admin#23]
node 16
使用pnpm install & pnpm ru ndev 或者 yarn install & yarn run dev
出来以后登录页面，登录框的样式明显不正确
![image](https://user-images.githubusercontent.com/9667153/185288450-698e7e88-0731-4d0a-b627-d33e43ca282f.png)

**Comment by hsiangleev** [comment]
可能是安装版本不一致导致的吧，我也没用pnpm或yarn安装，那用npm安装也不行吗
