### ISSUE TITLE
如果要支持IE，要怎么配置

### ISSUE THREAD

**Issue by qiuchsh** [hsiangleev/element-plus-admin#3]
用IE11打开，一片空白，也不报错

**Comment by hsiangleev** [comment]
@qiuchsh 因为是用的vue3，他现在还没有支持ie11来，所以现在只能用现代浏览器打开

**Comment by qiuchsh** [comment]
@hsiangleev @vitejs/plugin-legacy 这个插件是不是可以支持IE呢，有下面这么一段介绍

Note: this plugin requires vite@^2.0.0-beta.12.

Vite's default browser support baseline is Native ESM. This plugin provides support for legacy browsers that do not support native ESM.

**Comment by hsiangleev** [comment]
@qiuchsh 这个应该是让vite支持IE11的吧，但是vuejs3不支持的话应该还是不行的吧，我再看看
