### ISSUE TITLE
导航栏能不能支持多级或者1级

### ISSUE THREAD

**Issue by lonerwolf** [hsiangleev/element-plus-admin#4]
比如首页，不要group，单单一个菜单就行，不需要打开内部菜单

**Comment by hsiangleev** [comment]
@lonerwolf 这个应该可以支持，这两天有时间的时候加一下

**Comment by hsiangleev** [comment]
@lonerwolf 添加了一个alwaysShow的配置，默认子菜单个数为1个的时候会自动将子菜单当成父菜单显示
